# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

      
    - name: Install dependencies
      run: |
        PROTOC_VERSION=25.6
        PROTOC_ZIP=protoc-${PROTOC_VERSION}-linux-x86_64.zip
        wget https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/${PROTOC_ZIP}
        unzip -o ${PROTOC_ZIP} -d protoc3
        sudo mv protoc3/bin/* /usr/local/bin/
        sudo mv protoc3/include/* /usr/local/include/
        rm -f ${PROTOC_ZIP}
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

    - name: Build
      run: make

    - name: Create artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: ./akademi