# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

      
    - name: Install dependencies
      run: |
        PROTOC_VERSION=25.6
        PROTOC_ZIP=protoc-${PROTOC_VERSION}-linux-x86_64.zip
        wget https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/${PROTOC_ZIP}
        unzip -o ${PROTOC_ZIP} -d protoc3
        sudo mv protoc3/bin/* /usr/local/bin/
        sudo mv protoc3/include/* /usr/local/include/
        rm -f ${PROTOC_ZIP}
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

    - name: Build
      run: make

    - name: Create artifact
      uses: actions/upload-artifact@v4
      with:
        name: akademi-linux-x86_64-"${{ github.ref }}"
        path: ./akademi

    - name: Build Docker
      run: make docker

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/akademi
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        [ "$VERSION" == "main" ] && VERSION=latest
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag akademi $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION